; Listing generated by Microsoft (R) Optimizing Compiler Version 19.37.32822.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__1735BEE6_Multiply@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Log@@YAPEBDPEBD@Z				; Log
PUBLIC	?Multiply@@YAHHH@Z				; Multiply
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_08EOBDLMOI@Multiply@			; `string'
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Log@@YAPEBDPEBD@Z DD imagerel $LN4
	DD	imagerel $LN4+30
	DD	imagerel $unwind$?Log@@YAPEBDPEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Multiply@@YAHHH@Z DD imagerel $LN4
	DD	imagerel $LN4+54
	DD	imagerel $unwind$?Multiply@@YAHHH@Z
pdata	ENDS
;	COMDAT ??_C@_08EOBDLMOI@Multiply@
CONST	SEGMENT
??_C@_08EOBDLMOI@Multiply@ DB 'Multiply', 00H		; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Multiply@@YAHHH@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Log@@YAPEBDPEBD@Z DD 020601H
	DD	030023206H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Multiply@@YAHHH@Z
_TEXT	SEGMENT
a$ = 48
b$ = 56
?Multiply@@YAHHH@Z PROC					; Multiply, COMDAT
; File C:\Dev\CppTutorialCherno\HelloWorld\Multiply.cpp
; Line 7
$LN4:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	edi, ecx
	mov	ebx, edx
	lea	rcx, OFFSET FLAT:__1735BEE6_Multiply@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rcx, OFFSET FLAT:??_C@_08EOBDLMOI@Multiply@
	call	?Log@@YAPEBDPEBD@Z			; Log
	imul	edi, ebx
	mov	rbx, QWORD PTR [rsp+48]
	mov	eax, edi
; Line 10
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?Multiply@@YAHHH@Z ENDP					; Multiply
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Log@@YAPEBDPEBD@Z
_TEXT	SEGMENT
message$ = 48
?Log@@YAPEBDPEBD@Z PROC					; Log, COMDAT
; File C:\Dev\CppTutorialCherno\HelloWorld\Multiply.cpp
; Line 2
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	lea	rcx, OFFSET FLAT:__1735BEE6_Multiply@cpp
	call	__CheckForDebuggerJustMyCode
	mov	rax, rbx
; Line 4
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?Log@@YAPEBDPEBD@Z ENDP					; Log
_TEXT	ENDS
END
